### ISSUE TITLE
signup doesnt work

### ISSUE THREAD

**Issue by orangessssssss** [yukiqt/bwitter#3]
Warning: Undefined array key "time_zone" in C:\xampp\htdocs\signup.php on line 30

Warning: Undefined variable $response in C:\xampp\htdocs\signup.php on line 49

Warning: Undefined variable $file in C:\xampp\htdocs\signup.php on line 63

Fatal error: Uncaught ValueError: Path cannot be empty in C:\xampp\htdocs\signup.php:63 Stack trace: #0 C:\xampp\htdocs\signup.php(63): getimagesize('') #1 {main} thrown in C:\xampp\htdocs\signup.php on line 63

**Comment by orangessssssss** [comment]
last one is solvable though you do have to upload a profile pic

**Comment by CraftedRllRl** [comment]
The first one is solvable by adding a timezone in the sql
