### ISSUE TITLE
Sign Up doesnt work still

### ISSUE THREAD

**Issue by CraftedRllRl** [yukiqt/bwitter#4]
I try to sign up and I get this error:

Warning: Undefined variable $response in C:\xampped\htdocs\signup.php on line 49

Fatal error: Uncaught Error: Call to undefined function imagecreatefromstring() in C:\xampped\htdocs\signup.php:64 Stack trace: #0 {main} thrown in C:\xampped\htdocs\signup.php on line 64

**Comment by ashley-graves** [comment]
Make sure you have the PHP GD extension enabled

https://stackoverflow.com/a/70319131
Sincerely,
Yuki.
[https://cdn.possum.city/uploads/44792a27-f425-42c0-8499-574b0654623a.gif]

May 10, 2023 6:35:41 PM CraftedRllRl ***@***.***>:

**Comment by CraftedRllRl** [comment]
Now it's giving only the first error

![image](https://github.com/yukiqt/bwitter/assets/121927131/66b98fde-3306-4900-ab03-d22e788cfa20)

**Comment by ashley-graves** [comment]
make sure you set the captcha key in
https://github.com/yukiqt/bwitter/blob/ef30bae07b26692bbd40bbce5a633d8e1156967c/inc/main.php#L248
and
https://github.com/yukiqt/bwitter/blob/ef30bae07b26692bbd40bbce5a633d8e1156967c/signup.php#L208
Sincerely,
Yuki.
[https://cdn.possum.city/uploads/44792a27-f425-42c0-8499-574b0654623a.gif]

May 10, 2023 6:49:15 PM CraftedRllRl ***@***.***>:

**Comment by CraftedRllRl** [comment]
thanks it works now

**Comment by ashley-graves** [comment]
no problem!
