### ISSUE TITLE
Cant Edit profile

### ISSUE THREAD

**Issue by CraftedRllRl** [yukiqt/bwitter#5]
sorry for adding another problem, but I can't edit my profile and I get this:

Warning: Undefined variable $file in C:\xampped\htdocs\edit.php on line 33

Deprecated: getimagesize(): Passing null to parameter #1 ($filename) of type string is deprecated in C:\xampped\htdocs\edit.php on line 33

Fatal error: Uncaught ValueError: Path cannot be empty in C:\xampped\htdocs\edit.php:33 Stack trace: #0 C:\xampped\htdocs\edit.php(33): getimagesize('') #1 {main} thrown in C:\xampped\htdocs\edit.php on line 33

**Comment by ashley-graves** [comment]
shoulf be fixed in 2d9b514

**Comment by CraftedRllRl** [comment]
yep, it works! thanks, and sorry for bothering

**Comment by ashley-graves** [comment]
no worries
Sincerely,
Yuki.
[https://cdn.possum.city/uploads/44792a27-f425-42c0-8499-574b0654623a.gif]
