### ISSUE TITLE
Signing up without a picture errors

### ISSUE THREAD

**Issue by CraftedRllRl** [yukiqt/bwitter#6]
When I do I get this error:

Warning: Undefined variable $file in C:\xampped\htdocs\signup.php on line 63

Deprecated: getimagesize(): Passing null to parameter #1 ($filename) of type string is deprecated in C:\xampped\htdocs\signup.php on line 63

Fatal error: Uncaught ValueError: Path cannot be empty in C:\xampped\htdocs\signup.php:63 Stack trace: #0 C:\xampped\htdocs\signup.php(63): getimagesize('') #1 {main} thrown in C:\xampped\htdocs\signup.php on line 63

**Comment by ashley-graves** [comment]
should be fixed in 89bc582

**Comment by CraftedRllRl** [comment]
thanks now it works
