### ISSUE TITLE
can't connect the database

### ISSUE THREAD

**Issue by sinopdrivers** [yukiqt/bwitter#8]
i try to import sql but i get error 
Error
SQL query:

CREATE DATABASE `twitter` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
MySQL said: Documentation

#1044 - Access denied for user 'm6773_yottube2'@'%.devil' to database 'twitter'

**Comment by ashley-graves** [comment]
This is an issue with your SQL server, not with the script.
Please consult the manual for whatever you are using.

**Comment by sinopdrivers** [comment]
@ashley-graves i'm not wrong tho i created database and when import with sql it gets error, you should fix this

**Comment by sinopdrivers** [comment]
i use phpmyadmin it's not having issues on my sql server

**Comment by ashley-graves** [comment]
This is not an issue with this project.
